### ISSUE TITLE
How is date / time stored in trophy files?

### ISSUE THREAD

**Issue by SilicaAndPina** [darkautism/PS3TrophyIsGood#1]
i am trying to make a simular app to this for the psvita, i have mananged to decrypt a trophy data file and the timestamp looks like this:
E2 24 07 8B C0 CA 66 under a hex editor. i cant seem to figure out how this actually relates to the time set i can change some things and the time will change on the system but i cant control how it will change 

i think its probably simular to ps3.. so how does it work there ?

**Comment by darkautism** [comment]
Hi SilicaAndPina,

You can use library [TROPHYParser](https://github.com/darkautism/TROPHYParser) which i impilement for parse PS3 Thropy.

PS3 system use Cell as it's CPU, and Cell's register format is `Big Endian`. So we need convert it to `Little Endian`. After you convert it to `Little Endian`, it should been UNIX timestamp.

I do not study PS vita's architecture so i'm not very sure PS vita's CPU is `Big Endian`. You can trying to convert by some UNIX timestamp tools.

Timestamp parser should in this file:
https://github.com/darkautism/TROPHYParser/blob/e2e3ad5211fcaa2052190a3b226f7c2ddd5e8bad/TROPHYParser/TROPUSR.cs#L347

**Comment by SilicaAndPina** [comment]
PSVita has an ARM Processor. 
which according to a google search can be either . . . (unless.. google is wrong?)
UNIX  timestamps dont seem to work as-is
i could try converting it from Big to Little Endain i suppose..
its also possible im looking at the wrong data and thinking its a timestamp . . .

**Comment by SilicaAndPina** [comment]
ok so the vita is little endain. BUT its not using a UNIX timestamp.. its using something else..
i made a plugin awhile ago to unlock all trophys instantly (just for loops through the list)
trophy #1:
63082238521902556
trophy #2:
63082238522656535
i think        ^^ is the seconds since it goes up by one each trophy and it takes about 1 second to run sceNpTrophyUnlockTrophy. not quite sure what format this is..

**Comment by darkautism** [comment]
What time was 63082238522656535 display in ps vita?
Diff two timestamp that we can know how to parse this timestamp.

**Comment by SilicaAndPina** [comment]
There all from TropHAX (a plugin that unlocks every trophy in a game)

Trophy #1:
63653109374899251
2/2/2018 8:16AM
Trophy #2
63653109375790203
2/2/2018 18:16AM
Trophy #3
63653109376644633
2/2/2018 18:16AM
Trophy #4
63653109377492984
2/2/2018 8:16AM
Trophy #5
63653109378308334
2/2/2018 8:16AM

etc.. etc.

**Comment by SilicaAndPina** [comment]
ah i figures out the format:
its the number of microseconds since 0001/01/01
