### ISSUE TITLE
Errors when loading trophy data from RPCS3

### ISSUE THREAD

**Issue by Vahkiti** [darkautism/PS3TrophyIsGood#17]
RPCS3 saves its trophy data in some way that's just ever so slightly different then a standard PS3 trophy file. I'm not sure exactly how, but it will always result in the following errors when trying to load it: 

```
Open failed:Cannot open TROPUSR.DAT

Open failed:Value cannot be null.
Parameter name: dest
```

Both of these errors seem to alternate. Ie: if you open the file it'll display the first one, then switch to the second if you try to open it again. RPCS3 does not display time stamps in its trophy manager which makes it REALLY annoying for me to try and copy trophies from there back to my actual PS3 since with the way this bugs out, I just have to guess at an approximate earned date and time.

**Comment by Vahkiti** [comment]
From Sonic Unleashed:
[NPWR00507_00.zip](https://github.com/darkautism/PS3TrophyIsGood/files/6550246/NPWR00507_00.zip)

**Comment by Vahkiti** [comment]
Another error it'll sometimes give:
`Open failed:Data on the root level is invalid. Line 1, position 1.
Open failed:Cannot open TROPCONF.SFM`

**Comment by jhonathanc** [comment]
Great, I will check it out. But where is the other files? TROPTRNS.DAT and PARAM.SFO that should exists on folder? Even the images are missing... really weird.

**Comment by Vahkiti** [comment]
Apologies, I realized I forgot the images and updated the link. The param.sfo however is never generated by RPCS3.

**Comment by jhonathanc** [comment]
Ok, will check it out. I don't think the PARAM.SFO is needed to open... Thanks.

**Comment by jhonathanc** [comment]
Weird, even the TROPTRNS.DAT is missing...
About "Open failed:Data on the root level is invalid. Line 1, position 1." error, it occurs because the TROPCONF.SFM "header" don't have the first 64 bytes, but I can fix it. But the TROPTRNS.DAT should be there... I will check if I can ignore this and use only TROPUSR.DAT.

**Comment by Vahkiti** [comment]
Yeah it's strange. I'm not entirely sure what that file does, as I'm not super versed on the technical stuff in PS3 modding, but all I know is that RPCS3 neither generates, nore presumably reads it.

**Comment by darkautism** [comment]
In ps3 BD has a trp file. This folder seems only extract trp file and do not contains real trophy files.
This is a trp extractor which i write long time ago.
https://github.com/darkautism/PS3TRPExtractor

I think RPCS3 only emulate got trophy and extractor it but do not really generate a vaild TROPTRNS.DAT.

**Comment by jhonathanc** [comment]
I checked TROPUSR.DAT, it contains the achieved trophies, but none time stamp... I don't think it's a problem with PS3TrophyIsGood after all...

**Comment by Vahkiti** [comment]
Damn, that is a shame. I borught this up with the RPCS3 devs a while ago and they seemingly just kinda shrugged it off. Guess I'm back to just manually writing down the time as I see it. THanks for the help anyways guys. :)

**Comment by jhonathanc** [comment]
Don't worry, it helps a lot. I'm writing a code to let people open this kind of trophies. But even If TROPUSR.DAT has the correct timestamps, probably we should write some code to create TROPTRNS.DAT from scratch (I checked the code and probably it's not difficult). I will let this issue open until I end my write up.

**Comment by jhonathanc** [comment]
@Vahkiti I wrote a suggestion on RPCS3 to fix the "timestamp issue" on TROPUSR.DAT. I don't know the RPCS3 code to say if it's difficult or not... Let's see what they will decide. I think as RPCS3 don't use PSN, they don't care about the trophies (no one would try to sync them on RPCS3).

**Comment by Vahkiti** [comment]
Aye, which makes sense, but as I pointed out, some people will find the tools, (in this case YOUR tools. :p) to MAKE them sync one way or another. It's just a shame that it's so close, but otherwise generates a partially invalid file. I've also found that IMPORTING a real trophy list will actually be read initially, but entirely wiped the moment an in-game trophy trigger is hit. Not really a you problem, but just one more thing making this difficult.

**Comment by jhonathanc** [comment]
I've build a new test version, that can open that weird trophy set. You will not be able to save it properly (yet), but if the RPCS3 fix the issue to set the timestamp of trophies, at least you will be able to copy (manually) the timestamps to a valid trophy set:

https://www.mediafire.com/file/hhkxpe3wdsffwfj/PS3TrophyIsGood.zip/file

Probably let people save the "RPCS3 trophy set" will be a little more difficult than I thought, because TROPUSR.DAT is also with a lot of information missing.

The code for this version is not on my repo yet, because I'm still trying to "forge" these files (TROPUSR.DAT and TROPTRNS.DAT) properly.

**Comment by darkautism** [comment]
TROPUSR.DAT is a template file, so it do not contains timestamp that makes sense.
The real PS3 will copy template file as TROPTRNS.DAT and edit it.

**Comment by jhonathanc** [comment]
I don't think TROPUSR.DAT is only a template file, because it contains valid timestamps. Because TROPUSR.DAT has the timestamps of achieved (and synchronized) trophies on other PS3, that don't exist on TROPTRNS.DAT. I know TROPCONF.SCM is a template file, without timestamps. About TROPTRNS.DAT, it has a list of achieved trophies, but only from the PS3 that it has been extracted.

**Comment by darkautism** [comment]
It make sense. But we still not edit TROPUSR.DAT because it store synced trophies. This file should edit by PS3 and PSN after synced.

**Comment by Kilowog01** [comment]
The program crashes when I try to save or unlock any trophy.
Please add support for RPCS3 trophy files
[NPWR01210_00.zip](https://github.com/darkautism/PS3TrophyIsGood/files/6759193/NPWR01210_00.zip)

**Comment by jhonathanc** [comment]
@Kilowog01 it's not PS3TrophyIsGood fault. It's RPCS3 fault.

**Comment by Kilowog01** [comment]
@jhonathanc Couldn't you guys try to make a pull request that minimally fixes this? This is not a priority for them. I know your work is C and C# while RPCS3 is C++, but you guys know the structure of the files, you know how to debug them, you will certainly be luckier than me who know almost nothing about C++.

**Comment by jhonathanc** [comment]
@Kilowog01, the problem is not open the file, the problem is that there is no timestamps on it (the RPCS3 don't store the times as it should), so all efforts to open the file is useless because the file is "almost" empty (it only contains info about what trophy is unlocked, and nothing else).

**Comment by mitch03** [comment]
any luck? ive been trying to unlock trophies on RPCS3 but cannot :(
