### ISSUE TITLE
How is the Progress Indicator calculated?

### ISSUE THREAD

**Issue by SilicaAndPina** [darkautism/PS3TrophyIsGood#2]
Progress on psvtrophyisgood, absolutely everything works trophys sync online and everything, however theres an issue and thats that the progress bar on the trophy set doesnt update to respect the new trophys. 
for example, it can show 0% and have all trophys unlocked when you click on it,
PSN doesnt care about this and will sync it anyway, but id like to fix it regardless.
i found the offset in TRPTITLE that controls this data, but i have no idea how it is calculated besides that
FF FF FF FF is 100%.

How is this calculated on ps3?

**Comment by darkautism** [comment]
I found some code in my project. 

## unlock
```C#
trophyListInfo.AchievementRate[id / 32] |= (uint)(1 << id).ChangeEndian();
AchievementRate[id / 32] |= (uint)(1 << id);
```

## lock
```C#
trophyListInfo.AchievementRate[id / 32] &= 0xFFFFFFFF ^ (uint)(1 << id).ChangeEndian();
AchievementRate[id / 32] &= 0xFFFFFFFF ^ (uint)(1 << id);
```

Hope this helps.

**Comment by SilicaAndPina** [comment]
thanks, the changeEndain part isnt needed for me . but aside from that this is helpfull
