### ISSUE TITLE
un-Representable DateTime.

### ISSUE THREAD

**Issue by flavio-fsa200x** [darkautism/PS3TrophyIsGood#30]
I Got this error: " The added or subtracted value results in an un-Representable DateTime. Parameter name: value" 

Is there a Way to fix it ?
![Error](https://user-images.githubusercontent.com/109383371/179288105-e84c41d7-f8f2-4a8b-b4c8-0ccc32b566f0.png)

**Comment by jdfr228** [comment]
I got this error after trying to use Apollo to modify my trophy set for a game, and then attempting to switch to this after it didn't work right on the percentage tracking.  Did you use Apollo as well?

**Comment by flavio-fsa200x** [comment]
No, didn't used Apollo before this.

**Comment by flavio-fsa200x** [comment]
I found out what happened:
In my case, trophies had already been acquired and registered/sync. on another PS3 other than the one I was on now.
Solution: Delete the trophy list for the game mentioned on the Current PS3. Starting the game before synchronizing trophies will now result in an empty trophy list. Update the trophies from this list in the application (trophyisgood)  and synchronize again on the PSN, from this point on the list will work normally.
