### ISSUE TITLE
Is it safe? Anyone ban? 

### ISSUE THREAD

**Issue by MrDwarf-95** [darkautism/PS3TrophyIsGood#31]
Hi, i'm thinking of using this program but...will be safe? Can you tell your experiences?

Thanks!

**Comment by Rage4Dayz96** [comment]
It's mostly safe, but there is always a chance of you getting banned while doing it as you need to sign in to sync the trophies. Just make sure you do legit timestamps and disable the syscalls before signing onto PSN
