### ISSUE TITLE
off-topic

### ISSUE THREAD

**Issue by bucanero** [darkautism/PS3TrophyIsGood#4]
hello @darkautism 

I'm working on improving my PS3 save tool [Apollo](https://github.com/bucanero/apollo-ps3) and I'm planning to add some trophy editing options. I'm reviewing your sources to understand better how the `TROP*` files are structured, so if you have any specific comment or thing to be aware please let me know.

Thanks for sharing your sources!

**Comment by darkautism** [comment]
Hi, Bucanero,

Your project looks amazing. I'm very glad that my source code is helpful. I do not have PS3 now and do not research with PlayStation data format anymore so I can't give you any advice. Wish you success in project Apollo.

**Comment by DarkNacho** [comment]
Hi, I still have my ps3 and I would gladly help you to add support to trophies.

**Comment by bucanero** [comment]
> Hi, Bucanero,
> 
> Your project looks amazing. I'm very glad that my source code is helpful. I do not have PS3 now and do not research with PlayStation data format anymore so I can't give you any advice. Wish you success in project Apollo.

thanks for your comments @darkautism ! I'm still working on my app to extend the trophy support. Hopefully I'll be able to "translate" the C# code from this project and use it on Apollo. :)
Have a nice day !

**Comment by bucanero** [comment]
> Hi, I still have my ps3 and I would gladly help you to add support to trophies.

sure, all help is welcomed 👍  also for testing having someone with a PS3 to run tests would be great too
feel free to jump into the Apollo repository so we can follow up

thanks
