### ISSUE TITLE
Linux compatibility 

### ISSUE THREAD

**Issue by hachikoQ** [darkautism/PS3TrophyIsGood#5]
Hello is there any way get it run on Linux?

**Comment by darkautism** [comment]
Try [mono](https://www.mono-project.com/docs/getting-started/install/linux/) or wine?

**Comment by hachikoQ** [comment]
i tried! cant access it need .NET Framework to work theres no way get it to linux.

**Comment by hachikoQ** [comment]
Anyway i've seen you updated it 1.3.7 , still using 1.2.6 im able to update it ? there's no easy .exe download im lost

**Comment by darkautism** [comment]
> Anyway i've seen you updated it 1.3.7 , still using 1.2.6 im able to update it ? there's no easy .exe download im lost

https://github.com/darkautism/PS3TrophyIsGood/actions/runs/580453998

I add auto-build in this project. You can download the newest version in artifacts.
![image](https://user-images.githubusercontent.com/3898040/108462066-e8c87e00-72b6-11eb-80e1-1447c9cc2c2a.png)

**Comment by darkautism** [comment]
> i tried! cant access it need .NET Framework to work theres no way get it to linux.

I do not run it in Linux before so I didn't know how to resolve it. Maybe you can recompile this project with the mono compiler or use qemu to running a windows instance to run this program.

**Comment by hachikoQ** [comment]
Thank you!

**Comment by hachikoQ** [comment]
Very cool features! Well done
