### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Demask70** [darkautism/PS3TrophyIsGood#6]
Hi, I'm experimenting with your tool and discovered the following:

1) If you unlock trophies for a certain game using two different consoles (_A & B,_ to be clearer), when you open in PS3TrophyIsGood **the trophy folder downloaded from _console "A"_**, **you see as "LOCKED" and apparently "NOT SYNCED" all the trophies you unlocked and synced from _console "B"_**. 
This happens even if all the trophies are correctly synced to PSN (so does each single trophy stores the _console_id_ info?)

2) If you click on "Instant Platinum", you get an **Unhandled Exception**

3) if you try to correct the timestamp of a specific trophy, you get the same "**Unhandled Exception**" unless you input a "recent" date: **you can't input a date older than 15 days from today**

I think you are aware of this "limit" (or "check") because, in the Unhandled Exception window, I can read a chinese message I roughly translated with "Already synced with PSN, try a later date"

Why does this happen?
Is there a way to see as "GET" and "SYNCED" every trophy unlocked with two or more consoles?

Last...
Excuse me... Is there a way to download the *.exe of the version 1.3.7? 
I can't, at the moment, compile the code.

Thank you in advance for your answer and for your great job!

**Comment by darkautism** [comment]
1. This seems like a cool bug. I do not have a PS3 console a long time ago so I can't help anymore.

2&3. It seems the trophy parser is detected your trophy is already synced
https://github.com/darkautism/TROPHYParser/blob/53540c1ec605790f390b4ea92a540b673038f098/TROPHYParser/TROPTRNS.cs#L183

If You wanna remove this check, just remove this line, or if statement to prevent Exception. But I do not sure sync to PSN causes a ban if the user already synced. I didn't know the PSN server-side has double synced detection.


https://github.com/darkautism/PS3TrophyIsGood/actions/runs/580453998

I add auto-build in this project. You can download the newest version in artifacts.
![image](https://user-images.githubusercontent.com/3898040/108462066-e8c87e00-72b6-11eb-80e1-1447c9cc2c2a.png)
